name: Build xdph (Nix)

on: [push, pull_request, workflow_dispatch]
jobs:
  nix:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v27

    - name: Build xdg-desktop-portal-hyprland
      run: nix build --print-build-logs --extra-substituters "https://hyprland.cachix.org"
